### ISSUE TITLE
Convert to using a homogenized, cached backend

### ISSUE THREAD

**Issue by halfwit** [ubqt-systems/ircfs#1]
@alyptik lemme know what you think of this.
So, essentially the idea is to allow something like the following

```
# Join a channel
touch "$XDG_RUNTIME_DIR/web/irc/irc.freenode.net/#ubqt"

# Join a server
mkdir "$XDG_RUNTIME_DIR/web/irc/irc.freenode.net"

```

Right now, it uses a config file to join channels and such; we could switch to just an rc (shell script) for setup.
This does introduce the need for an intermediate server that handles clients connecting in, negotiating what `feed` `status` `title` and others will contain for that client; but in my opinion it's better to have it separated out from the back-ends. Means we won't have to write that logic over and over again and again, just switching buffers to that `web/irc/irc.freenode.net/#ubqt` would handle everything, and there's then nothing stopping someone from changing buffers to `web/https/www.google.com/` and browse the web, then tab back all within the same client session.

**Comment by halfwit** [comment]
To implement this, it'd basically be that you have just one fancy webfs that runs all the different back-ends.

**Comment by halfwit** [comment]
We could just drop raw IRC messages here, like what II has; and the intermediate server can worry about translating that to useful markdown/files

**Comment by alyptik** [comment]
I like this idea a lot; theoretically, how is switching buffers gonna be handled?

**Comment by halfwit** [comment]
The intermediate program will basically parse these files and send them to a client on demand.

**Comment by halfwit** [comment]
What it'd mean for this particular repo is that it becomes more like ii, not doing any of the 9p stuff.

**Comment by alyptik** [comment]
I like it a lot! A damn fine idea; now i just need to get on top of learning Go

**Comment by halfwit** [comment]
With this, the only thing that would have to be in Go would be the intermediate server. The rest of it could be written in whatever

**Comment by halfwit** [comment]
I'm still brainstorming the idea, not 100% sure i want to introduce
complexity
